# -*- coding: utf-8 -*-
"""17.servidor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGJKSD8YKhn5LPv6awfpTojrs9xZhJE5

Prof. Fernando Amaral

www.eia.ai

# Criando uma API
"""

!pip install flask_ngrok

!pip install pyngrok

!ngrok config add-authtoken SEU_CODIGO_AQUI

from flask import Flask, jsonify, request
from pyngrok import ngrok

app = Flask(__name__)

@app.route('/')
def padrao():
  return "Escolha um dos métodos"

@app.route('/cotacao/')
def cotacao():
  return '5.34'

@app.route('/conversao/<float:val>')
def conversao(val):
  return str(val * 5.34)

@app.route('/cotacaocompleta', methods=['GET'])
def cotacaocompleta():
  argumentos = request.args
  valor = float(argumentos.get('valor'))
  mes = argumentos.get('mes')

  total = 0.0
  if mes == 'Janeiro':
    total = valor * 5.34
  elif mes == 'Fevereiro':
    total = valor * 5.22
  elif mes == 'Marco':
    total = valor * 5.19

  return str(total)

@app.route('/tabela/')
def tabela():
  return jsonify(Janeiro='5.34',Fevereiro='5.22', Marco='5.33')

if __name__ == '__main__':
    port = 5000
    public_url = ngrok.connect(port)
    print(' * ngrok tunnel "{}" -> "http://127.0.0.1:{}/"'.format(public_url, port))

    try:
        app.run(port=port)
    except KeyboardInterrupt:
        ngrok.disconnect(public_url)